<?php
// Path: resources/views/layouts/print.php

/**
 * @var string $locale
 * @var string $documentTitle
 * @var string $content
 * @var array $companyInfo
 */

$dir = ($locale === 'ar') ? 'rtl' : 'ltr';
$companyInfo = $companyInfo ?? [
    'name' => 'NOUR TRUST',
    'slogan' => 'IT DEVELOPMENT & WEB SOLUTIONS',
    'tax_no' => '300000000000003',
    'address' => 'Cairo, Egypt',
    'phone' => '+20 100 123 4567',
    'email' => 'info@nourtrust.com'
];
?>
<!DOCTYPE html>
<html lang="<?= $locale ?>" dir="<?= $dir ?>">
<head>
    <meta charset="UTF-8">
    <title><?= htmlspecialchars($documentTitle ?? 'Document') ?> | NOUR TRUST</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --color-primary-900: #0f172a;
            --color-primary-500: #2563eb;
            --color-text-main: #1e293b;
            --color-text-muted: #64748b;
            --color-border: #e2e8f0;
        }
        body {
            font-family: <?= $locale === 'ar' ? "'Cairo', sans-serif" : "'Inter', sans-serif" ?>;
            color: var(--color-text-main);
            margin: 0;
            padding: 0;
            background: #fff;
            font-size: 10pt;
            line-height: 1.5;
        }
        @page { size: A4; margin: 15mm; }
        .print-container { width: 100%; max-width: 210mm; margin: 0 auto; background: #fff; }
        .print-header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid var(--color-primary-900); padding-bottom: 15px; margin-bottom: 20px; }
        .brand-name { font-size: 24pt; font-weight: 700; color: var(--color-primary-900); letter-spacing: 1px; margin: 0; line-height: 1; }
        .brand-slogan { font-size: 8pt; color: var(--color-text-muted); letter-spacing: 0.5px; margin-top: 4px; }
        .company-details { text-align: end; font-size: 8pt; color: var(--color-text-muted); }
        .document-title { font-size: 16pt; font-weight: 700; color: var(--color-primary-500); margin: 0 0 15px 0; text-transform: uppercase; }
        
        table.print-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.print-table th { background: #f8fafc; color: var(--color-text-muted); font-weight: 600; text-transform: uppercase; font-size: 8pt; padding: 8px; border: 1px solid var(--color-border); text-align: start; }
        table.print-table td { padding: 8px; border: 1px solid var(--color-border); font-size: 9pt; }
        .text-end { text-align: end !important; }
        .font-bold { font-weight: 700 !important; }
        
        .print-footer { margin-top: 40px; border-top: 1px solid var(--color-border); padding-top: 10px; font-size: 8pt; color: var(--color-text-muted); text-align: center; }
        
        @media print {
            body { background: transparent; }
            .print-container { box-shadow: none; max-width: none; }
        }
    </style>
</head>
<body>
    <div class="print-container">
        <!-- Header -->
        <div class="print-header">
            <div>
                <h1 class="brand-name"><?= htmlspecialchars($companyInfo['name']) ?></h1>
                <div class="brand-slogan"><?= htmlspecialchars($companyInfo['slogan']) ?></div>
            </div>
            <div class="company-details">
                <div>VAT: <?= htmlspecialchars($companyInfo['tax_no']) ?></div>
                <div><?= htmlspecialchars($companyInfo['address']) ?></div>
                <div><?= htmlspecialchars($companyInfo['phone']) ?> | <?= htmlspecialchars($companyInfo['email']) ?></div>
            </div>
        </div>

        <!-- Content (Document Specific) -->
        <?= $content ?>

        <!-- Footer -->
        <div class="print-footer">
            Generated by NOUR TRUST ERP Enterprise System on <?= date('Y-m-d H:i:s') ?>
        </div>
    </div>
</body>
</html>